version: 2.1
jobs:
  build-deploy-test:
    working_directory: ~/iiv-admin
    docker:
      - image: circleci/node:12.16-stretch
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e5:40:22:66:5d:fc:60:a8:92:bf:8d:98:3d:4d:19:90"
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run:
          name: Deploy
          command: |
            ssh-keyscan $SSH_HOST_TEST >> ~/.ssh/known_hosts
            scp -r ./dist/* $SSH_USER_TEST@$SSH_HOST_TEST:/home/iiv/docker/iiv.ux.uz/test/admin

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy-test:
          filters:
            branches:
              only: test